export const LP_VARIABLES = [
  {
    id: "VariableID:5432:369",
    name: "background/primary",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:429",
    name: "background/secondary",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:430",
    name: "background/Inverse/primary",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:431",
    name: "background/Inverse/secondary",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:432",
    id:"VariableID:9ad37631600a63b2f36f7ac5e40aea95f94e4f99/6055:506"
    name: "background/brand",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:434",
    name: "background/negative",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:435",
    name: "background/postive",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:436",
    name: "background/light/brand",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:437",
    name: "background/light/negative",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:438",
    name: "background/light/postive",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:439",
    name: "background/light/warning",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:440",
    name: "background/overlay",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:442",
    name: "background/pressed/primary-button",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:443",
    name: "background/pressed/secondary-button",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:444",
    name: "border/primary",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:445",
    name: "border/selected",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:446",
    name: "border/inverse",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:447",
    name: "border/brand",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:448",
    name: "border/negative",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:450",
    name: "border/postive",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:451",
    name: "content/primary",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:452",
    name: "content/secondary",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:453",
    name: "content/tertiary",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:456",
    name: "content/inactive",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:457",
    name: "content/inverse-primary",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:459",
    name: "content/negative",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:460",
    name: "content/warning",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:461",
    name: "content/postive",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5434:478",
    name: "background/warning",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
];

[
  {
    id: "VariableID:5432:369",
    name: "background/primary",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:429",
    name: "background/secondary",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:430",
    name: "background/Inverse/primary",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:431",
    name: "background/Inverse/secondary",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:432",
    name: "background/brand",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:434",
    name: "background/negative",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:435",
    name: "background/postive",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:436",
    name: "background/light/brand",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:437",
    name: "background/light/negative",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:438",
    name: "background/light/postive",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:439",
    name: "background/light/warning",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:440",
    name: "background/overlay",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:442",
    name: "background/pressed/primary-button",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:443",
    name: "background/pressed/secondary-button",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:444",
    name: "border/primary",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:445",
    name: "border/selected",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:446",
    name: "border/inverse",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:447",
    name: "border/brand",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:448",
    name: "border/negative",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:450",
    name: "border/postive",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:451",
    name: "content/primary",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:452",
    name: "content/secondary",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:453",
    name: "content/tertiary",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:456",
    name: "content/inactive",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:457",
    name: "content/inverse-primary",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:459",
    name: "content/negative",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:460",
    name: "content/warning",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5432:461",
    name: "content/postive",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
  {
    id: "VariableID:5434:478",
    name: "background/warning",
    description: "",
    type: "COLOR",
    scopes: ["ALL_SCOPES"],
    hiddenFromPublishing: false,
    codeSyntax: {},
  },
];

// Predefined array of colors to match against
export const LP_COLORS = [
  "#F2E6FF",
  "#ECFDF5",
  "#FFEBF0",
  "#F2E6FF",
  "#F5F5F5",
  "#EEEEEE",
  "#E5E5E5",
  "#D4D4D4",
  "#A3A3A3",
  "#737373",
  "#525252",
  "#404040",
  "#262626",
  "#171717",
  "#FFF0F4",
  "#FFD6E0",
  "#FFAFC3",
  "#FF7E9E",
  "#EE537A",
  "#DB2855",
  "#9F183A",
  "#740924",
  "#510216",
  "#2A0A12",
  "#F2E6FF",
  "#CCA2FC",
  "#A973F0",
  "#8649E3",
  "#6422D6",
  "#4400C9",
  "#3100A3",
  "#21007D",
  "#140057",
  "#0A0030",
  "#000000",
  "#FFFFFF",
  "#ECFDF5",
  "#D1FAE5",
  "#A7F3D0",
  "#6EE7B7",
  "#34D399",
  "#10B981",
  "#05A372",
  "#047555",
  "#05523C",
  "#042E23",
  "#FFF1F1",
  "#FFD7D9",
  "#FFB3B8",
  "#FF8389",
  "#FA4D56",
  "#DA1E28",
  "#A2191F",
  "#750E13",
  "#520408",
  "#2D0709",
  "#FFFBEB",
  "#FEF3C7",
  "#FDE68A",
  "#FCD34D",
  "#FBBF24",
  "#F59E0B",
  "#C46C05",
  "#8C4107",
  "#5E2909",
  "#301306",
];
